/** Site copy in English and Arabic. `en` defines the shape; `ar` must match it. */

export const en = {
  meta: {
    langName: "العربية",
    langShort: "AR",
  },
  nav: {
    home: "Home",
    stories: "Success stories",
    dashboard: "Dashboard",
    clients: "Our clients",
    about: "About",
    contact: "Contact",
    demo: "Live demo",
    cta: "Start a campaign",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    theme: "Switch theme",
    language: "Switch language",
  },
  footer: {
    blurb: "Influencer campaigns planned, managed, and measured end to end across 52+ countries.",
    tagline: "Right creators. Right audiences. Clear campaigns.",
    explore: "Explore",
    company: "Company",
    aboutUs: "About us",
    contactUs: "Contact us",
    markets: "Markets",
    marketsBody: "Saudi Arabia · Kuwait · United Arab Emirates · Qatar · Bahrain — and 47 more.",
    rights: "All rights reserved.",
  },
  common: {
    countries: "Countries",
    reach: "Follower reach",
    creators: "Creators",
    brandsServed: "Brands served",
    followers: "Combined creator following",
    years: "Years",
    campaigns: "Campaigns delivered",
    countriesReached: "Countries reached",
    yearsRunning: "Years running campaigns",
    viewClients: "View our clients",
    allStories: "Explore all campaigns",
    planCampaign: "Plan your campaign",
    startCampaign: "Start a campaign",
    seeStories: "See campaign results",
    play: "Play the film",
    pause: "Pause the film",
  },
  markets: {
    Egypt: "Egypt",
    Kuwait: "Kuwait",
    Qatar: "Qatar",
    "Saudi Arabia": "Saudi Arabia",
    "United Arab Emirates": "United Arab Emirates",
    Bahrain: "Bahrain",
  } as Record<string, string>,
  categories: {
    All: "All",
    Restaurant: "Restaurant",
    Café: "Café",
    Fashion: "Fashion",
    Beauty: "Beauty",
  } as Record<string, string>,
  home: {
    title: "Niche Mastery Redefined | ELITƎ",
    description:
      "ELITƎ builds selective creator partnerships around the right niche, audience, and brand ambition.",
    heroLine1: "Niche Mastery",
    heroLine2: "Redefined.",
    heroBody: "Elite creator partnerships, built around the right niche.",
    heroCta: "Plan an elite partnership",
    networkStat: "Niche creators",
    heroAlt: "Guests at an exclusive rooftop dinner overlooking a Gulf skyline",
    trusted: "Trusted by brands across the Gulf and beyond",
    whyEyebrow: "The ELITƎ standard",
    whyLine1: "Selective partnerships",
    whyLine2: "built around the right niche.",
    whyBody:
      "Every partnership starts with niche relevance, audience fit, and a clear brand ambition.",
    pillars: [
      {
        title: "Flat Rate",
        body: "A clear commercial model for premium creator partnerships, built to plan with confidence.",
      },
      {
        title: "Tailored Solutions",
        body: "A selective approach shaped around your brand, niche, market, and ambition.",
      },
      {
        title: "BUZZ",
        body: "Activate a focused group of niche creators to build precise, immediate momentum.",
      },
      {
        title: "MAINTAIN",
        body: "Sustain brand relevance through consistent partnerships with carefully selected creators.",
      },
    ],
    servicesEyebrow: "Elite partnership services",
    servicesLine1: "Everything needed to build",
    servicesLine2: "the right niche partnership.",
    servicesBody:
      "Strategy, selective creator curation, content, and reporting work as one considered process.",
    services: [
      {
        title: "Niche creator curation",
        body: "Select creators whose audience, market, category, and content style fit your brand ambition.",
      },
      {
        title: "Partnership strategy",
        body: "Turn your objectives, niche, market, timing, and budget into a clear campaign plan.",
      },
      {
        title: "Elite creator content",
        body: "Selected creators produce content in their own voice, aligned with your brief and brand standards.",
      },
      {
        title: "Campaign stewardship",
        body: "Follow delivery while the campaign is live and receive clear reporting when it ends.",
      },
    ],
    filmEyebrow: "Campaigns on film",
    filmBody: "See the work behind each selective partnership.",
    filmAlt: "A creator filming a plated dish in a dimly lit fine-dining restaurant",
    processEyebrow: "How it works",
    processLine1: "Four considered steps",
    processLine2: "from niche to impact.",
    step: "Step",
    steps: [
      {
        title: "Match",
        body: "We match your brand with niche creators whose audience, market, and content style fit the ambition.",
      },
      {
        title: "Plan",
        body: "We turn your goals, market, timing, deliverables, and budget into a clear campaign plan.",
      },
      {
        title: "Create",
        body: "Selected creators produce authentic content in their own voice, aligned with your brand guidelines.",
      },
      {
        title: "Measure",
        body: "Track published content as it happens, then review delivery, reach, and campaign performance in clear reports.",
      },
    ],
    storiesEyebrow: "Campaigns in action",
    storiesLine1: "See niche partnerships",
    storiesLine2: "in action.",
    reelsEyebrow: "Campaign films",
    reelsLine1: "See the work,",
    reelsLine2: "not just the numbers.",
    dashEyebrow: "The ELITƎ dashboard",
    dashLine1: "Your campaign,",
    dashLine2: "clear at a glance.",
    dashPoints: [
      "Follow every selected creator from invitation to published content",
      "See stories, posts, and videos in one place",
      "Manage curated shortlists, branches, and niche creator check-ins",
      "Get live campaign support when you need it",
    ],
    ctaLine1: "Ready to plan",
    ctaLine2: "your next campaign?",
    ctaBody:
      "Tell us your ambition. We’ll shape the right niche, creator partnership, and campaign plan.",
    skylineAlt: "Gulf city skyline at night",
  },
  about: {
    title: "About ELITƎ | Creator campaigns across 52+ countries",
    description:
      "For more than ten years, ELITƎ has helped brands plan and run creator campaigns across 52+ countries.",
    eyebrow: "About ELITƎ",
    heroLine1: "A decade of building influence",
    heroLine2: "across markets.",
    heroBody:
      "For more than ten years, ELITƎ has helped brands plan and run creator campaigns across 52+ countries — combining market knowledge, creator relationships, and clear campaign management.",
    missionEyebrow: "What we do",
    missionTitle: "Make influencer marketing easier to plan, run, and measure.",
    missionBody:
      "We build creator strategies around your audience and campaign goals, then manage the work from creator selection to reporting.",
    approachEyebrow: "Our approach",
    approachTitle: "Right creator. Right audience. Right moment.",
    approachBody:
      "We start with who you need to reach, then choose the creators, market plan, and campaign execution that best support that goal.",
    quote: "The right creator, in the right market, at the right moment.",
    figureAlt: "A creator capturing a fine-dining dish for a brand campaign",
    whyEyebrow: "Why brands work with ELITƎ",
    whyLine1: "Built for clarity,",
    whyLine2: "scale, and control.",
    reasons: [
      {
        title: "Proven experience",
        body: "More than ten years of hands-on campaign experience across markets and categories.",
      },
      {
        title: "Market reach",
        body: "A creator network across more than 52 countries gives you room to grow across markets.",
      },
      {
        title: "Audience-led creator matching",
        body: "Creator selection starts with audience fit and campaign goals, not follower count alone.",
      },
      {
        title: "Clear measurement",
        body: "Follow campaign delivery and review performance through structured reporting.",
      },
      {
        title: "Hands-on support",
        body: "A campaign team supports the process from planning through delivery and reporting.",
      },
    ],
    ctaLine1: "Let’s plan",
    ctaLine2: "your next campaign.",
    ctaBody:
      "Tell us your goal and target market. We’ll help you shape the creator approach and next steps.",
  },
  clients: {
    title: "Our clients | ELITƎ",
    description:
      "Brands across the Gulf and beyond work with ELITƎ to reach audiences through carefully matched creators.",
    eyebrow: "Our clients",
    heroLine1: "Brands that trust ELITƎ",
    heroLine2: "with their campaigns.",
    heroBody:
      "From hospitality and beauty to fashion, automotive, and lifestyle, brands across the Gulf and beyond work with ELITƎ to reach relevant audiences.",
    roster: "Client roster",
    brands: "brands",
    search: "Search by brand name",
    emptyTitle: "No brands match that name.",
    emptyBody: "Clear the search to see all brands.",
    ctaLine1: "Want to see",
    ctaLine2: "your brand here?",
    ctaButton: "Start a campaign",
  },
  stories: {
    title: "Campaigns in action | ELITƎ",
    description: "Explore ELITƎ campaigns by market and see the creator scale behind each one.",
    eyebrow: "Campaigns in action",
    heroLine1: "See real ELITƎ campaigns",
    heroLine2: "at a glance.",
    heroBody:
      "Explore campaigns by market and see the creator scale behind each one. Filter by market to find campaigns relevant to you.",
    heroAlt:
      "Guests admiring curated brand activations and luxury showcases at an exclusive evening awards exhibition in Riyadh",
    featured: "Featured campaigns",
    filmsEyebrow: "Campaign films",
    filmsLine1: "Watch the campaigns",
    filmsLine2: "in action.",
    ctaLine1: "Ready to build",
    ctaLine2: "your own campaign?",
  },
  contact: {
    title: "Start a campaign — Contact ELITƎ",
    description:
      "Share your brand, target market, and campaign goal with ELITƎ to plan the right creator approach and next steps.",
    eyebrow: "Start a campaign",
    heroLine1: "Tell us what you want",
    heroLine2: "to achieve.",
    heroBody:
      "Share your brand, target market, and campaign goal. We’ll review the brief and come back with a recommended creator approach and next steps.",
    points: [
      "Access to 85K+ creators across 52+ countries",
      "End-to-end campaign planning and management",
      "Live campaign tracking and clear reporting",
    ],
    fields: {
      name: "Full name",
      namePh: "Your name",
      brand: "Brand / company",
      brandPh: "Brand or company name",
      email: "Work email",
      emailPh: "you@company.com",
      market: "Target market",
      marketPh: "Saudi Arabia, Kuwait, UAE…",
      goal: "Campaign goal",
      goalPh: "What do you want this campaign to achieve?",
    },
    submit: "Send campaign brief",
    sentTitle: "Thanks — your campaign brief has been sent.",
    sentBody: "Our team will review it and get back to you soon.",
  },
  platform: {
    title: "Dashboard | ELITƎ",
    description:
      "Manage branches, creators, campaign stages, and published content in one ELITƎ workspace.",
    hero: {
      heading: "One workspace for every campaign.",
      tag: "The ELITƎ dashboard",
      lede: "See branches, creators, campaign stages, and published content in one place, so your team always knows what is happening next.",
      ctaPrimary: "Explore the live demo",
      ctaSecondary: "Book a walkthrough",
    },
    demo: {
      note: "Demo data is illustrative. Switch between campaigns to explore the workspace.",
      switchAriaLabel: "Choose a dashboard demo campaign",
      viewLaunch: "Summer launch",
      viewGrowth: "Always-on growth",
      viewOpening: "New location",
      campaign: "Summer launch · Riyadh",
      period: "01–30 Jun 2026",
    },
    kpis: {
      branchesLabel: "Branches",
      branchesSub: "Per location reporting",
      creatorsLabel: "Saved creators",
      creatorsSub: "Profiles saved by your team",
      campaignsLabel: "Campaigns",
      campaignsSub: "Live and scheduled",
      coverageLabel: "Published content",
      coverageSub: "Stories, posts, and videos",
    },
    overview: {
      eyebrow: "Creator progress",
      heading: "Know where every creator stands.",
      lede: "Follow each creator from first contact to published content without chasing updates across messages and spreadsheets.",
      pipelineAriaLabel: "Creator campaign stages",
    },
    pipeline: {
      pending: "Pending",
      confirmed: "Confirmed",
      visited: "Visited",
      delivered: "Delivered",
      postCreation: "Post creation",
      shared: "Shared",
      covered: "Covered",
    },
    panels: {
      recentCampaigns: "Sample campaigns",
      recentCampaignsBadge: "Demo data",
      coverageDetails: "Published content",
      coverageTotal: "346 pieces",
      story: "Story",
      post: "Post",
      video: "Video",
      coverageNote:
        "Published content is grouped by format and updates with the selected demo campaign.",
    },
    features: {
      eyebrow: "Inside the platform",
      heading: "Built to keep campaign teams in control.",
      influencersTitle: "Creators & shortlists",
      influencersCopy:
        "Browse creators, save profiles, and build shortlists your team can use together.",
      branchesTitle: "Branches",
      branchesCopy: "Track creator activity and published content separately for each location.",
      scannerTitle: "Creator check-ins",
      scannerCopy:
        "Confirm creator arrivals with a quick scan and keep location activity up to date.",
      campaignsTitle: "Campaigns",
      campaignsCopy:
        "Follow every campaign from brief and approval through execution and published content.",
      reportingTitle: "Reporting",
      reportingCopy:
        "Review campaign delivery by creator and content format, ready to share with stakeholders.",
      supportTitle: "Live support",
      supportCopy: "Get help from the campaign team when you need it.",
    },
    cta: {
      heading: "See how the workspace fits your campaign.",
      copy: "Book a walkthrough and explore the platform around your own campaign needs.",
      button: "Book a walkthrough",
    },
  },
} as const;

type DeepMutable<T> = T extends readonly (infer U)[]
  ? DeepMutable<U>[]
  : T extends string
    ? string
    : T extends object
      ? { -readonly [K in keyof T]: DeepMutable<T[K]> }
      : T;

export type Content = DeepMutable<typeof en>;

export const ar: Content = {
  meta: {
    langName: "English",
    langShort: "EN",
  },
  nav: {
    home: "الرئيسية",
    stories: "قصص النجاح",
    dashboard: "لوحة التحكم",
    clients: "عملاؤنا",
    about: "عن ELITƎ",
    contact: "تواصل معنا",
    demo: "النسخة التجريبية",
    cta: "ابدأ حملة",
    openMenu: "افتح القائمة",
    closeMenu: "أغلق القائمة",
    theme: "تغيير المظهر",
    language: "تغيير اللغة",
  },
  footer: {
    blurb:
      "حملات تسويق عبر المؤثرين نخطط لها ونديرها ونقيس نتائجها من البداية إلى النهاية في أكثر من ٥٢ دولة.",
    tagline: "صُنّاع المحتوى المناسبون. الجمهور المناسب. حملات أوضح.",
    explore: "استكشف",
    company: "الشركة",
    aboutUs: "عن ELITƎ",
    contactUs: "تواصل معنا",
    markets: "الأسواق",
    marketsBody: "السعودية · الكويت · الإمارات العربية المتحدة · قطر · البحرين — و٤٧ دولة أخرى.",
    rights: "جميع الحقوق محفوظة.",
  },
  common: {
    countries: "دولة",
    reach: "إجمالي الوصول عبر المتابعين",
    creators: "صُنّاع محتوى",
    brandsServed: "علامات تجارية تم خدمتها",
    followers: "إجمالي متابعي صُنّاع المحتوى",
    years: "سنوات",
    campaigns: "حملات منفذة",
    countriesReached: "دول تم الوصول إليها",
    yearsRunning: "سنوات في إدارة الحملات",
    viewClients: "تعرّف على عملائنا",
    allStories: "استكشف كل الحملات",
    planCampaign: "خطّط لحملتك",
    startCampaign: "ابدأ حملة",
    seeStories: "شاهد نتائج الحملات",
    play: "تشغيل الفيلم",
    pause: "إيقاف الفيلم",
  },
  markets: {
    Egypt: "مصر",
    Kuwait: "الكويت",
    Qatar: "قطر",
    "Saudi Arabia": "المملكة العربية السعودية",
    "United Arab Emirates": "الإمارات العربية المتحدة",
    Bahrain: "البحرين",
  },
  categories: {
    All: "الكل",
    Restaurant: "مطاعم",
    Café: "مقاهي",
    Fashion: "أزياء",
    Beauty: "تجميل",
  },
  home: {
    title: "إتقان التخصص، بمفهوم جديد | ELITƎ",
    description:
      "تبني ELITƎ شراكات منتقاة مع صُنّاع محتوى متخصصين حول المجال والجمهور وطموح العلامة.",
    heroLine1: "إتقان التخصص",
    heroLine2: "بمفهوم جديد.",
    heroBody: "شراكات مع نخبة صُنّاع المحتوى، مبنية حول التخصص الأنسب.",
    heroCta: "خطّط لشراكة نوعية",
    networkStat: "صُنّاع محتوى متخصصون",
    heroAlt: "ضيوف في عشاء خاص على سطح يطل على أفق مدينة خليجية",
    trusted: "تثق بنا علامات تجارية في الخليج وخارجه",
    whyEyebrow: "معيار ELITƎ",
    whyLine1: "شراكات منتقاة",
    whyLine2: "مبنية حول التخصص الأنسب.",
    whyBody: "تبدأ كل شراكة بملاءمة التخصص والجمهور، وتنطلق من طموح واضح للعلامة.",
    pillars: [
      {
        title: "Flat Rate",
        body: "نموذج تجاري واضح لشراكات نوعية مع صُنّاع المحتوى، يسهّل التخطيط بثقة.",
      },
      {
        title: "حلول مخصّصة",
        body: "نهج انتقائي مصمم حول علامتك وتخصصك وسوقك وطموحك.",
      },
      {
        title: "BUZZ",
        body: "فعّل مجموعة مركّزة من صُنّاع المحتوى المتخصصين لبناء زخم دقيق وفوري.",
      },
      {
        title: "MAINTAIN",
        body: "حافظ على صلة علامتك بالجمهور عبر شراكات مستمرة مع صُنّاع محتوى منتقين بعناية.",
      },
    ],
    servicesEyebrow: "خدمات شراكات ELITƎ",
    servicesLine1: "كل ما يلزم لبناء",
    servicesLine2: "الشراكة الأنسب للتخصص.",
    servicesBody:
      "تعمل الاستراتيجية وانتقاء صُنّاع المحتوى والمحتوى والتقارير ضمن رحلة واحدة مدروسة.",
    services: [
      {
        title: "انتقاء صُنّاع محتوى متخصصين",
        body: "نختار صُنّاع محتوى يتوافق جمهورهم وسوقهم وفئتهم وأسلوبهم مع طموح علامتك.",
      },
      {
        title: "استراتيجية الشراكة",
        body: "نحوّل أهدافك وتخصصك والسوق والجدول الزمني والميزانية إلى خطة حملة واضحة.",
      },
      {
        title: "محتوى نخبة صُنّاع المحتوى",
        body: "ينشئ صُنّاع المحتوى المنتقون محتواهم بأسلوبهم الطبيعي، بما يتوافق مع تفاصيل الحملة ومعايير علامتك.",
      },
      {
        title: "إدارة الشراكة",
        body: "تابع التنفيذ أثناء الحملة واحصل على تقرير واضح بعد انتهائها.",
      },
    ],
    filmEyebrow: "الحملات بالفيديو",
    filmBody: "شاهد العمل وراء كل شراكة منتقاة.",
    filmAlt: "مبدع يصور طبقاً في مطعم فاخر بإضاءة خفيفة",
    processEyebrow: "كيف تعمل الحملة؟",
    processLine1: "أربع خطوات مدروسة",
    processLine2: "من التخصص إلى الأثر.",
    step: "خطوة",
    steps: [
      {
        title: "نختار",
        body: "نطابق علامتك مع صُنّاع محتوى متخصصين يتناسب جمهورهم وسوقهم وأسلوبهم مع طموحك.",
      },
      {
        title: "نخطّط",
        body: "نحوّل أهدافك والسوق والتوقيت والمخرجات والميزانية إلى خطة حملة واضحة.",
      },
      {
        title: "ننفّذ",
        body: "ينشئ صُنّاع المحتوى المنتقون محتوى طبيعيًا بأسلوبهم، مع الالتزام بإرشادات علامتك.",
      },
      {
        title: "نقيس",
        body: "تابع المحتوى المنشور أثناء الحملة، ثم راجع التنفيذ والوصول والأداء في تقارير واضحة.",
      },
    ],
    storiesEyebrow: "حملات على أرض الواقع",
    storiesLine1: "شاهد الشراكات المتخصصة",
    storiesLine2: "على أرض الواقع.",
    reelsEyebrow: "فيديوهات الحملات",
    reelsLine1: "شاهد التنفيذ،",
    reelsLine2: "وليس الأرقام فقط.",
    dashEyebrow: "لوحة تحكم ELITƎ",
    dashLine1: "حملتك واضحة أمامك",
    dashLine2: "من مكان واحد.",
    dashPoints: [
      "تابع كل صانع محتوى منتقى من الدعوة حتى نشر المحتوى",
      "شاهد القصص والمنشورات والفيديوهات في مكان واحد",
      "أدر القوائم المنتقاة والفروع وتسجيل وصول صُنّاع المحتوى المتخصصين",
      "احصل على دعم مباشر للحملة عند الحاجة",
    ],
    ctaLine1: "مستعد لتخطيط",
    ctaLine2: "حملتك القادمة؟",
    ctaBody: "أخبرنا بطموحك، وسنحدد التخصص الأنسب وشراكة صُنّاع المحتوى وخطة الحملة.",
    skylineAlt: "أفق مدينة خليجية ليلاً",
  },
  about: {
    title: "عن ELITƎ | حملات صُنّاع المحتوى في أكثر من ٥٢ دولة",
    description:
      "لأكثر من عشر سنوات، ساعدت ELITƎ العلامات التجارية على تخطيط وإدارة حملات صُنّاع المحتوى في أكثر من ٥٢ دولة.",
    eyebrow: "عن ELITƎ",
    heroLine1: "أكثر من عشر سنوات من بناء التأثير",
    heroLine2: "عبر أسواق متعددة.",
    heroBody:
      "لأكثر من عشر سنوات، ساعدت ELITƎ العلامات التجارية على تخطيط وإدارة حملات صُنّاع المحتوى في أكثر من ٥٢ دولة، بالاعتماد على فهم الأسواق وعلاقات صُنّاع المحتوى وإدارة واضحة للحملات.",
    missionEyebrow: "ما الذي نقدمه؟",
    missionTitle: "نجعل التسويق عبر المؤثرين أسهل في التخطيط والتنفيذ والقياس.",
    missionBody:
      "نبني استراتيجية صُنّاع المحتوى حول جمهورك وأهداف حملتك، ثم ندير الرحلة من الاختيار حتى التقارير.",
    approachEyebrow: "منهجنا",
    approachTitle: "صانع المحتوى المناسب. الجمهور المناسب. في الوقت المناسب.",
    approachBody:
      "نبدأ بتحديد الجمهور الذي تريد الوصول إليه، ثم نختار صُنّاع المحتوى وخطة السوق والتنفيذ الأنسب لهذا الهدف.",
    quote: "صانع المحتوى المناسب، في السوق المناسب، وفي الوقت المناسب.",
    figureAlt: "مبدع يصور طبقاً فاخراً لحملة علامة تجارية",
    whyEyebrow: "لماذا تعمل العلامات التجارية مع ELITƎ؟",
    whyLine1: "تجربة مبنية على الوضوح",
    whyLine2: "والنطاق والتحكم.",
    reasons: [
      {
        title: "خبرة مثبتة",
        body: "أكثر من عشر سنوات من الخبرة العملية في إدارة الحملات عبر أسواق وقطاعات مختلفة.",
      },
      {
        title: "انتشار في أسواق متعددة",
        body: "تمنحك شبكة صُنّاع المحتوى في أكثر من ٥٢ دولة مساحة أكبر للتوسع بين الأسواق.",
      },
      {
        title: "اختيار يبدأ من الجمهور",
        body: "يبدأ اختيار صُنّاع المحتوى من ملاءمة الجمهور وهدف الحملة، وليس من عدد المتابعين فقط.",
      },
      {
        title: "قياس واضح",
        body: "تابع تنفيذ الحملة وراجع أداءها من خلال تقارير منظمة وواضحة.",
      },
      {
        title: "دعم عملي",
        body: "يساندك فريق الحملة من مرحلة التخطيط حتى التنفيذ والتقارير.",
      },
    ],
    ctaLine1: "لنخطط",
    ctaLine2: "لحملتك القادمة.",
    ctaBody: "أخبرنا بهدفك والسوق المستهدف، وسنساعدك في تحديد أسلوب الحملة والخطوات التالية.",
  },
  clients: {
    title: "عملاؤنا | ELITƎ",
    description:
      "تعمل علامات تجارية في الخليج وخارجه مع ELITƎ للوصول إلى جماهير أكثر صلة بأهدافها.",
    eyebrow: "عملاؤنا",
    heroLine1: "علامات تجارية تثق بـ ELITƎ",
    heroLine2: "في إدارة حملاتها.",
    heroBody:
      "من الضيافة والجمال إلى الأزياء والسيارات ونمط الحياة، تعمل علامات تجارية في الخليج وخارجه مع ELITƎ للوصول إلى جماهير أكثر صلة بأهدافها.",
    roster: "قائمة العملاء",
    brands: "علامة تجارية",
    search: "ابحث باسم العلامة التجارية",
    emptyTitle: "لا توجد علامات تجارية مطابقة.",
    emptyBody: "امسح البحث لعرض جميع العلامات.",
    ctaLine1: "هل تريد أن تكون",
    ctaLine2: "علامتك هنا؟",
    ctaButton: "ابدأ حملة",
  },
  stories: {
    title: "حملات على أرض الواقع | ELITƎ",
    description: "تصفّح حملات ELITƎ حسب السوق وتعرّف على حجم مشاركة صُنّاع المحتوى في كل حملة.",
    eyebrow: "حملات على أرض الواقع",
    heroLine1: "استكشف حملات ELITƎ الحقيقية",
    heroLine2: "بسهولة.",
    heroBody:
      "تصفّح الحملات حسب السوق وتعرّف على حجم مشاركة صُنّاع المحتوى في كل حملة. صفِّ الحملات حسب السوق للوصول إلى أمثلة أقرب لاحتياجك.",
    heroAlt: "ضيوف يستعرضون معروضات العلامات الفاخرة في معرض وحفل جوائز حصري بالرياض",
    featured: "حملات مختارة",
    filmsEyebrow: "فيديوهات الحملات",
    filmsLine1: "شاهد الحملات",
    filmsLine2: "أثناء التنفيذ.",
    ctaLine1: "جاهز لإطلاق",
    ctaLine2: "حملتك؟",
  },
  contact: {
    title: "ابدأ حملة — تواصل مع ELITƎ",
    description:
      "شارك علامتك والسوق المستهدف وهدف الحملة مع ELITƎ لتحديد أسلوب الحملة والخطوات التالية.",
    eyebrow: "ابدأ حملتك",
    heroLine1: "أخبرنا بما تريد",
    heroLine2: "تحقيقه.",
    heroBody:
      "شارك معنا علامتك والسوق المستهدف وهدف الحملة. سنراجع التفاصيل ونعود إليك باقتراح واضح لأسلوب الحملة والخطوات التالية.",
    points: [
      "الوصول إلى أكثر من ٨٥ ألف صانع محتوى في أكثر من ٥٢ دولة",
      "تخطيط وإدارة الحملة من البداية إلى النهاية",
      "متابعة مباشرة للحملة وتقارير واضحة",
    ],
    fields: {
      name: "الاسم الكامل",
      namePh: "اكتب اسمك",
      brand: "العلامة التجارية / الشركة",
      brandPh: "اسم العلامة التجارية أو الشركة",
      email: "بريد العمل",
      emailPh: "name@company.com",
      market: "السوق المستهدف",
      marketPh: "السعودية، الكويت، الإمارات…",
      goal: "هدف الحملة",
      goalPh: "ما الذي تريد أن تحققه هذه الحملة؟",
    },
    submit: "أرسل تفاصيل الحملة",
    sentTitle: "شكرًا لك. تم إرسال تفاصيل حملتك.",
    sentBody: "سيقوم فريقنا بمراجعتها والتواصل معك قريبًا.",
  },
  platform: {
    title: "لوحة تحكم ELITƎ",
    description:
      "أدر الفروع وصُنّاع المحتوى ومراحل الحملات والمحتوى المنشور من مساحة عمل واحدة في ELITƎ.",
    hero: {
      heading: "مساحة عمل واحدة لكل حملاتك.",
      tag: "لوحة تحكم ELITƎ",
      lede: "تابع الفروع وصُنّاع المحتوى ومراحل الحملات والمحتوى المنشور من مكان واحد، لتعرف أنت وفريقك دائمًا ما الذي يحدث وما الخطوة التالية.",
      ctaPrimary: "استكشف النسخة التجريبية",
      ctaSecondary: "احجز جولة تعريفية",
    },
    demo: {
      note: "البيانات المعروضة تجريبية. بدّل بين الحملات لاستكشاف مساحة العمل.",
      switchAriaLabel: "اختر حملة توضيحية للوحة التحكم",
      viewLaunch: "إطلاق الصيف",
      viewGrowth: "نمو مستمر",
      viewOpening: "فرع جديد",
      campaign: "إطلاق الصيف · الرياض",
      period: "1-30 يونيو 2026",
    },
    kpis: {
      branchesLabel: "الفروع",
      branchesSub: "تقارير لكل فرع",
      creatorsLabel: "صُنّاع المحتوى المحفوظون",
      creatorsSub: "ملفات حفظها فريقك",
      campaignsLabel: "الحملات",
      campaignsSub: "الجارية والمجدولة",
      coverageLabel: "المحتوى المنشور",
      coverageSub: "قصص ومنشورات وفيديوهات",
    },
    overview: {
      eyebrow: "تقدّم صُنّاع المحتوى",
      heading: "اعرف حالة كل صانع محتوى بسهولة.",
      lede: "تابع كل صانع محتوى من أول تواصل حتى نشر المحتوى دون الحاجة إلى البحث عن التحديثات بين الرسائل والجداول.",
      pipelineAriaLabel: "مراحل الحملة لصانع المحتوى",
    },
    pipeline: {
      pending: "قيد الانتظار",
      confirmed: "مؤكَّد",
      visited: "تمت الزيارة",
      delivered: "تم التسليم",
      postCreation: "إنشاء المحتوى",
      shared: "تم النشر",
      covered: "اكتملت التغطية",
    },
    panels: {
      recentCampaigns: "حملات تجريبية",
      recentCampaignsBadge: "بيانات تجريبية",
      coverageDetails: "المحتوى المنشور",
      coverageTotal: "346 قطعة محتوى",
      story: "ستوري",
      post: "منشور",
      video: "ريلز",
      coverageNote: "يُجمع المحتوى المنشور حسب النوع ويتحدّث مع الحملة التجريبية المختارة.",
    },
    features: {
      eyebrow: "داخل المنصة",
      heading: "صُممت لتمنح فرق الحملات رؤية وتحكمًا أوضح.",
      influencersTitle: "صُنّاع المحتوى والقوائم المختصرة",
      influencersCopy:
        "تصفّح صُنّاع المحتوى واحفظ الملفات المناسبة وأنشئ قوائم مختصرة يمكن لفريقك استخدامها معًا.",
      branchesTitle: "الفروع",
      branchesCopy: "تابع نشاط صُنّاع المحتوى والمحتوى المنشور لكل موقع بشكل منفصل.",
      scannerTitle: "تسجيل وصول صُنّاع المحتوى",
      scannerCopy: "أكّد وصول صُنّاع المحتوى بمسح سريع وحافظ على تحديث بيانات كل موقع.",
      campaignsTitle: "الحملات",
      campaignsCopy: "تابع كل حملة من تفاصيلها والموافقات حتى التنفيذ والمحتوى المنشور.",
      reportingTitle: "التقارير",
      reportingCopy:
        "راجع تنفيذ الحملة حسب صانع المحتوى ونوع المحتوى، ثم شارك النتائج بسهولة مع فريقك.",
      supportTitle: "الدعم المباشر",
      supportCopy: "احصل على مساعدة من فريق الحملة عندما تحتاج إليها.",
    },
    cta: {
      heading: "شاهد كيف تناسب مساحة العمل حملتك.",
      copy: "احجز جولة تعريفية واستكشف المنصة بناءً على احتياجات حملتك.",
      button: "احجز جولة تعريفية",
    },
  },
};

export const content = { en: en as unknown as Content, ar };
export type Lang = keyof typeof content;
